hotel:
  customer:
    username: MadameD
    password: boywithapple
    authorities: ROLE_CUSTOMER
  welcome:
    everyone: "Welcome to the hotel."
    room: "Welcome to your room."

server:
  port: 8200