server:
  port: 9200

rides:
  rides-users:
    - username: uberadmin
      password: uberadmin
      authorities: ROLE_ADMIN
    - username: uberapp
      password: uberapp
      authorities: ROLE_APP