server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb://localhost/qpl-profiler

profiler:
  messages:
    newPlayerSaved: New Player has been saved!
    totalEarningsUpdated: Total earnings have been updated!
    delete: Player has been deleted!
    notFound: Player not found!